# This workflow will build a golang project
name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.x"

      - name: Build
        run: go build -v ./...

      - name: Set up .env variables from secrets
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          echo "DB_HOST=${DB_HOST}" >> .env.test
          echo "DB_USER=${DB_USER}" >> .env.test
          echo "DB_PASSWORD=${DB_PASSWORD}" >> .env.test

      - name: Verify .env.test contents (debugging only)
        run: cat .env.test

      - name: Test
        run: go test -v ./...
